### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by jakeonrails** [joshuaclayton/homebrew-formulae#4]
macOS Sierra version 10.12.6 (16G1114) 
```
brew install unused
==> Installing unused from joshuaclayton/formulae
==> Downloading https://github.com/joshuaclayton/unused/archive/v0.8.0.0.tar.gz
Already downloaded: /Users/jakemoffatt/Library/Caches/Homebrew/unused-0.8.0.0.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/unused/0.8.0.0
Last 15 lines from /Users/jakemoffatt/Library/Logs/Homebrew/unused/04.cabal:
        PB.startProgress (PB.msg message) PB.percentage progressBarWidth
      In an equation for ‘buildProgressBar’:
          buildProgressBar
            = PB.startProgress (PB.msg message) PB.percentage progressBarWidth
            where
                message = "Working"
                progressBarWidth = 60
   |
50 |     PB.startProgress (PB.msg message) PB.percentage progressBarWidth
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
unused-0.8.0.0-4UdrPpi0V0xJo0hJCHOIzN failed during the building phase. The
exception was:
ExitFailure 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/joshuaclayton/homebrew-formulae/issues

These open issues may also help:
Unable to install (MacOS 10.12.2 -- unused 0.6.1.0) https://github.com/joshuaclayton/homebrew-formulae/issues/3
```

**Comment by gabebw** [comment]
Here are my logs from `brew install --verbose unused`. It's a long log, so I put it behind a `<details>` tag:

<details>
<summary>Log</summary>

==> Installing unused from joshuaclayton/formulae
/usr/bin/sandbox-exec -f /tmp/homebrew20180209-9405-byg6as.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/joshuaclayton/homebrew-formulae/Formula/unused.rb --verbose
==> Downloading https://github.com/joshuaclayton/unused/archive/v0.8.0.0.tar.gz
Already downloaded: /Users/gbwilliams/Library/Caches/Homebrew/unused-0.8.0.0.tar.gz
==> Verifying unused-0.8.0.0.tar.gz checksum
tar xzf /Users/gbwilliams/Library/Caches/Homebrew/unused-0.8.0.0.tar.gz
==> cabal sandbox init
Config file path source is default config file.
Config file
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal/config not
found.
Writing default configuration to
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal/config
Writing a default package environment file to
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/cabal.sandbox.config
Creating a new sandbox at
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal-sandbox
==> cabal update
Downloading the latest package list from hackage.haskell.org
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal-sandbox
Downloading base-compat-0.9.3...
Downloading colour-2.3.4...
Downloading dlist-0.8.0.4...
Configuring base-compat-0.9.3...
Downloading extensible-exceptions-0.1.1.4...
Configuring colour-2.3.4...
Configuring dlist-0.8.0.4...
Downloading file-embed-0.0.10.1...
Configuring extensible-exceptions-0.1.1.4...
Downloading integer-logarithms-1.0.2...
Configuring file-embed-0.0.10.1...
Downloading mtl-2.2.1...
Configuring integer-logarithms-1.0.2...
Downloading primitive-0.6.3.0...
Configuring mtl-2.2.1...
Configuring primitive-0.6.3.0...
Building colour-2.3.4...
Building dlist-0.8.0.4...
Building extensible-exceptions-0.1.1.4...
Building file-embed-0.0.10.1...
Building integer-logarithms-1.0.2...
Building mtl-2.2.1...
Building primitive-0.6.3.0...
Building base-compat-0.9.3...
Installed extensible-exceptions-0.1.1.4
Downloading random-1.1...
Configuring random-1.1...
Installed dlist-0.8.0.4
Downloading semigroups-0.18.4...
Configuring semigroups-0.18.4...
Installed file-embed-0.0.10.1
Downloading split-0.2.3.3...
Configuring split-0.2.3.3...
Building random-1.1...
Installed integer-logarithms-1.0.2
Downloading stm-2.4.5.0...
Configuring stm-2.4.5.0...
Building split-0.2.3.3...
Building semigroups-0.18.4...
Building stm-2.4.5.0...
Installed semigroups-0.18.4
Downloading terminal-size-0.3.2.1...
Configuring terminal-size-0.3.2.1...
Installed split-0.2.3.3
Downloading text-1.2.3.0...
Configuring text-1.2.3.0...
Installed mtl-2.2.1
Downloading th-abstraction-0.2.6.0...
Configuring th-abstraction-0.2.6.0...
Building terminal-size-0.3.2.1...
Building text-1.2.3.0...
Building th-abstraction-0.2.6.0...
Installed colour-2.3.4
Downloading time-locale-compat-0.1.1.3...
Configuring time-locale-compat-0.1.1.3...
Installed stm-2.4.5.0
Downloading transformers-compat-0.5.1.4...
Configuring transformers-compat-0.5.1.4...
Installed random-1.1
Downloading unliftio-core-0.1.1.0...
Building time-locale-compat-0.1.1.3...
Configuring unliftio-core-0.1.1.0...
Installed terminal-size-0.3.2.1
Downloading regex-base-0.93.2...
Configuring regex-base-0.93.2...
Building transformers-compat-0.5.1.4...
Installed time-locale-compat-0.1.1.3
Downloading ansi-terminal-0.8.0.1...
Configuring ansi-terminal-0.8.0.1...
Building unliftio-core-0.1.1.0...
Installed primitive-0.6.3.0
Downloading stm-chans-3.0.0.4...
Configuring stm-chans-3.0.0.4...
Installed transformers-compat-0.5.1.4
Downloading parallel-io-0.3.3...
Configuring parallel-io-0.3.3...
Building regex-base-0.93.2...
Building ansi-terminal-0.8.0.1...
Installed unliftio-core-0.1.1.0
Downloading vector-0.12.0.1...
Configuring vector-0.12.0.1...
Installed base-compat-0.9.3
Downloading tf-random-0.5...
Building parallel-io-0.3.3...
Configuring tf-random-0.5...
Building vector-0.12.0.1...
Installed th-abstraction-0.2.6.0
Downloading tagged-0.8.5...
Configuring tagged-0.8.5...
Building tf-random-0.5...
Installed regex-base-0.93.2
Downloading exceptions-0.8.3...
Configuring exceptions-0.8.3...
Building stm-chans-3.0.0.4...
Building tagged-0.8.5...
Installed parallel-io-0.3.3
Building exceptions-0.8.3...
Installed ansi-terminal-0.8.0.1
Downloading ansi-wl-pprint-0.6.8.2...
Configuring ansi-wl-pprint-0.6.8.2...
Installed stm-chans-3.0.0.4
Installed exceptions-0.8.3
Downloading resourcet-1.2.0...
Installed tagged-0.8.5
Building ansi-wl-pprint-0.6.8.2...
Installed tf-random-0.5
Downloading QuickCheck-2.10.1...
Configuring QuickCheck-2.10.1...
Configuring resourcet-1.2.0...
Building QuickCheck-2.10.1...
Building resourcet-1.2.0...
Installed ansi-wl-pprint-0.6.8.2
Downloading optparse-applicative-0.14.0.0...
Configuring optparse-applicative-0.14.0.0...
Building optparse-applicative-0.14.0.0...
Installed resourcet-1.2.0
Installed optparse-applicative-0.14.0.0
Installed QuickCheck-2.10.1
Installed text-1.2.3.0
Downloading parsec-3.1.13.0...
Downloading hashable-1.2.6.1...
Downloading blaze-builder-0.4.0.2...
Configuring parsec-3.1.13.0...
Configuring hashable-1.2.6.1...
Configuring blaze-builder-0.4.0.2...
Building parsec-3.1.13.0...
Building hashable-1.2.6.1...
Building blaze-builder-0.4.0.2...
Installed hashable-1.2.6.1
Downloading uuid-types-1.0.3...
Downloading unordered-containers-0.2.9.0...
Configuring unordered-containers-0.2.9.0...
Downloading scientific-0.3.5.2...
Configuring uuid-types-1.0.3...
Downloading async-2.2.1...
Configuring scientific-0.3.5.2...
Configuring async-2.2.1...
Installed blaze-builder-0.4.0.2
Building uuid-types-1.0.3...
Building unordered-containers-0.2.9.0...
Building scientific-0.3.5.2...
Building async-2.2.1...
Installed async-2.2.1
Downloading terminal-progress-bar-0.2...
Configuring terminal-progress-bar-0.2...
Installed uuid-types-1.0.3
Building terminal-progress-bar-0.2...
Installed terminal-progress-bar-0.2
Installed scientific-0.3.5.2
Downloading megaparsec-5.3.1...
Downloading attoparsec-0.13.2.2...
Configuring megaparsec-5.3.1...
Configuring attoparsec-0.13.2.2...
Installed parsec-3.1.13.0
Downloading regex-tdfa-1.2.2...
Configuring regex-tdfa-1.2.2...
Building megaparsec-5.3.1...
Building attoparsec-0.13.2.2...
Building regex-tdfa-1.2.2...
Installed vector-0.12.0.1
Downloading vector-algorithms-0.7.0.1...
Configuring vector-algorithms-0.7.0.1...
Building vector-algorithms-0.7.0.1...
Installed unordered-containers-0.2.9.0
Installed megaparsec-5.3.1
Downloading inflections-0.3.0.0...
Configuring inflections-0.3.0.0...
Building inflections-0.3.0.0...
Installed inflections-0.3.0.0
Installed attoparsec-0.13.2.2
Downloading cassava-0.4.5.1...
Downloading aeson-1.2.4.0...
Configuring cassava-0.4.5.1...
Configuring aeson-1.2.4.0...
Building cassava-0.4.5.1...
Building aeson-1.2.4.0...
Installed vector-algorithms-0.7.0.1
Downloading mono-traversable-1.0.8.1...
Configuring mono-traversable-1.0.8.1...
Building mono-traversable-1.0.8.1...
Installed cassava-0.4.5.1
Installed mono-traversable-1.0.8.1
Downloading conduit-1.3.0...
Configuring conduit-1.3.0...
Building conduit-1.3.0...
Installed conduit-1.3.0
Installed regex-tdfa-1.2.2
Installed aeson-1.2.4.0
Downloading yaml-0.8.28...
Configuring yaml-0.8.28...
Building yaml-0.8.28...
Installed yaml-0.8.28
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/unused/0.8.0.0
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal-sandbox
Configuring unused-0.8.0.0...
Building unused-0.8.0.0...
Failed to install unused-0.8.0.0
Build log ( /private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal-sandbox/logs/ghc-8.2.2/unused-0.8.0.0-AFDdHy0CnxDEIZgc9niJrz.log ):
cabal: Entering directory '.'
Configuring unused-0.8.0.0...
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Preprocessing library for unused-0.8.0.0..
Building library for unused-0.8.0.0..
[ 1 of 45] Compiling Common           ( src/Common.hs, dist/dist-sandbox-6777808f/build/Common.o )
[ 2 of 45] Compiling Unused.CLI.ProgressIndicator.Types ( src/Unused/CLI/ProgressIndicator/Types.hs, dist/dist-sandbox-6777808f/build/Unused/CLI/ProgressIndicator/Types.o )
[ 3 of 45] Compiling Unused.CLI.Util  ( src/Unused/CLI/Util.hs, dist/dist-sandbox-6777808f/build/Unused/CLI/Util.o )
[ 4 of 45] Compiling Unused.CLI.ProgressIndicator.Internal ( src/Unused/CLI/ProgressIndicator/Internal.hs, dist/dist-sandbox-6777808f/build/Unused/CLI/ProgressIndicator/Internal.o )

src/Unused/CLI/ProgressIndicator/Internal.hs:50:5: error:
    • Couldn't match type ‘async-2.2.1:Control.Concurrent.Async.Async
                             ()’
                     with ‘CC.ThreadId’
      Expected type: Integer -> IO (PB.ProgressRef, CC.ThreadId)
        Actual type: PB.Progress
                     -> IO
                          (PB.ProgressRef, async-2.2.1:Control.Concurrent.Async.Async ())
    • In the expression:
        PB.startProgress (PB.msg message) PB.percentage progressBarWidth
      In an equation for ‘buildProgressBar’:
          buildProgressBar
            = PB.startProgress (PB.msg message) PB.percentage progressBarWidth
            where
                message = "Working"
                progressBarWidth = 60
   |
50 |     PB.startProgress (PB.msg message) PB.percentage progressBarWidth
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
unused-0.8.0.0-AFDdHy0CnxDEIZgc9niJrz failed during the building phase. The
exception was:
ExitFailure 1

==> Formula
Tap: joshuaclayton/formulae
Path: /usr/local/Homebrew/Library/Taps/joshuaclayton/homebrew-formulae/Formula/unused.rb
==> Configuration
HOMEBREW_VERSION: 1.5.3-6-g646d696
ORIGIN: https://github.com/Homebrew/brew
HEAD: 646d696135e51c1b2e3cd7cd3d70cf9106ef3893
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc6e7485e89130b078a621caadde942c5610d25d
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/gbwilliams/.rbenv/shims/ruby => /Users/gbwilliams/.rbenv/versions/2.4.2/bin/ruby
Java: 1.8.0_131
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
Error: joshuaclayton/formulae/unused 0.8.0.0 did not build
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /private/tmp/unused-20180209-9407-1ymuznz/unused-0.8.0.0/.cabal-sandbox/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/ghc/bin:/usr/local/opt/cabal-install/bin:/usr/local/opt/pcre/bin:/usr/local/opt/xz/bin:/usr/local/opt/the_silver_searcher/bin:/usr/local/opt/ctags/bin:/usr/bin:/bin:/usr/sbin:/sbin

Logs:
     /Users/gbwilliams/Library/Logs/Homebrew/unused/02.cabal
     /Users/gbwilliams/Library/Logs/Homebrew/unused/04.cabal.cc
     /Users/gbwilliams/Library/Logs/Homebrew/unused/04.cabal
     /Users/gbwilliams/Library/Logs/Homebrew/unused/00.options.out
     /Users/gbwilliams/Library/Logs/Homebrew/unused/03.cabal.cc
     /Users/gbwilliams/Library/Logs/Homebrew/unused/01.cabal
     /Users/gbwilliams/Library/Logs/Homebrew/unused/03.cabal
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/joshuaclayton/homebrew-formulae/issues

These open issues may also help:
Unable to install (MacOS 10.12.2 -- unused 0.6.1.0) https://github.com/joshuaclayton/homebrew-formulae/issues/3
</details>

--------------------------

Interestingly, `stack install unused` (with an `lts-6.0` build plan) works, which might point towards a problem with Cabal's less-stringent version requirements? Stackage's LTS releases make sure that all the packages in that release work together, but (as I understand it) Cabal always uses the most-recent-possible versions. Maybe that's the problem?

**Comment by gabebw** [comment]
When I install with `stack`, it uses async 2.1.0 while Cabal uses async 2.2.1.

**Comment by gabebw** [comment]
Here's a diff of top-level packages installed by both. Red is cabal, green is stack:

```diff
-aeson-1.2.4.0
-attoparsec-0.13.2.2
+aeson-0.11.2.1
+attoparsec-0.13.0.2
 cassava-0.4.5.1
-conduit-1.3.0
+conduit-1.2.6.6
 inflections-0.3.0.0
-integer-logarithms-1.0.2
-megaparsec-5.3.1
-resourcet-1.2.0
-scientific-0.3.5.2
-yaml-0.8.28
+integer-logarithms-1
+megaparsec-5.1.2
+mmorph-1.0.9
+resourcet-1.1.7.4
+scientific-0.3.4.10
+yaml-0.8.17.1
```

**Comment by DmitryKK** [comment]
Similar problem

**Comment by VineethArvindFluke** [comment]
I'm facing same problem as well.

**Comment by aitor** [comment]
Exactly same problem.

**Comment by swordfish444** [comment]
same problem

**Comment by corasaurus-hex** [comment]
`stack install unused` using the `lts-6.0` resolver no longer works.

```
$ stack --resolver lts-6.0 install

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for async-2.1.0:
    base-4.11.1.0 from stack configuration does not match >=4.3 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> async-2.1.0

In the dependencies for cassava-0.4.5.1:
    base-4.11.1.0 from stack configuration does not match >=4.5 && <4.11  (latest matching version is 4.10.1.0)
needed due to unused-0.8.0.0 -> cassava-0.4.5.1

In the dependencies for exceptions-0.8.2.1:
    template-haskell-2.13.0.0 from stack configuration does not match >=2.2 && <2.12  (latest matching version is 2.11.1.0)
needed due to unused-0.8.0.0 -> exceptions-0.8.2.1

In the dependencies for hashable-1.2.4.0:
    base-4.11.1.0 from stack configuration does not match >=4.0 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> hashable-1.2.4.0

In the dependencies for optparse-applicative-0.12.1.0:
    process-1.6.3.0 from stack configuration does not match >=1.0 && <1.5  (latest matching version is 1.4.3.0)
needed due to unused-0.8.0.0 -> optparse-applicative-0.12.1.0

In the dependencies for primitive-0.6.1.0:
    base-4.11.1.0 from stack configuration does not match >=4.3 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> primitive-0.6.1.0

In the dependencies for scientific-0.3.4.6:
    base-4.11.1.0 from stack configuration does not match >=4.3 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> scientific-0.3.4.6

In the dependencies for stm-2.4.4.1:
    base-4.11.1.0 from stack configuration does not match >=4.3 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> stm-2.4.4.1

In the dependencies for tagged-0.8.4:
    template-haskell-2.13.0.0 from stack configuration does not match >=2.8 && <2.12  (latest matching version is 2.11.1.0)
needed due to unused-0.8.0.0 -> tagged-0.8.4

In the dependencies for transformers-compat-0.4.0.4:
    transformers-0.5.5.0 from stack configuration does not match >=0.4.1 && <0.5  (latest matching version is 0.4.3.0)
needed due to unused-0.8.0.0 -> transformers-compat-0.4.0.4

In the dependencies for vector-0.11.0.0:
    base-4.11.1.0 from stack configuration does not match >=4.3 && <4.10  (latest matching version is 4.9.1.0)
needed due to unused-0.8.0.0 -> vector-0.11.0.0

Some different approaches to resolving this:

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many complicated constraint
    errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps in /Users/nsutton/Code/tmp/unused/stack.yaml:

- base-4.9.1.0
- process-1.4.3.0
- template-haskell-2.11.1.0
- transformers-0.4.3.0

Plan construction failed.
```

**Comment by corasaurus-hex** [comment]
I also tried all the different approaches to no avail.

**Comment by joshuaclayton** [comment]
@nate @swordfish444 @aitor @VineethArvindFluke @DmitryKK @gabebw @jakeonrails mind giving this another go?

**Comment by gabebw** [comment]
Version 0.9 (the newest version) works for me!

**Comment by corasaurus-hex** [comment]
It installed via homebrew and I have it running right now. Thanks!
