### ISSUE TITLE
Cabal install failure

### ISSUE THREAD

**Issue by trevordmiller** [joshuaclayton/homebrew-formulae#5]
I was searching for a generic ctags dead code elimination tool and came across `unused`. It looks great! But I can't get it running. I tried to install `unused` with homebrew per the README instructions and am getting the following error:

`After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: primitive, vector, base, cassava, unused`

![image](https://user-images.githubusercontent.com/5497885/39413296-81afe262-4be5-11e8-82de-af868b0fb23f.png)

**Comment by jkthorne** [comment]
this is also happening to me

**Comment by brunoocasali** [comment]
I have macOS 10.13.5 and this still failing with the message about macOS 10.12.2 :|

**Comment by DamirSvrtan** [comment]
Any news on this? Would love to use unused.

**Comment by trevordmiller** [comment]
@joshuaclayton Sorry to bother but it seems a lot of people are running into this. Have you seen this?

**Comment by joshuaclayton** [comment]
@trevordmiller sorry for the delay - I've bumped the dependencies, mind giving this another try?

**Comment by trevordmiller** [comment]
@joshuaclayton Tried again using `brew tap joshuaclayton/formulae` then `brew install unused` with the following results:

![image](https://user-images.githubusercontent.com/5497885/45256747-1b38c780-b358-11e8-8aee-37c82a955a5d.png)

I already use ctags via `brew install universal-ctags`, not sure if that warning matters. But then it hangs indefinitely on `cabal install --jobs=4 --max-backjumps=100000 --only-dependencies`. I let it run for about 10 minutes before killing the process.

**Comment by trevordmiller** [comment]
Nevermind, tried again and it's working! Thanks for fixing :)
